### ISSUE TITLE
Pick up fluid not inputting fluid in hotbar as description says

### ISSUE THREAD

**Issue by genesy** [Alexthw46/StarbuncleMania#4] opened 2023-02-13 12:47 UTC
It just disappears. I tried with bucket and pneumatic tanks

**Comment by Alexthw46** [comment] 2023-02-13 13:43
Buckets are blacklisted because they don't work as intended, i'll have to check for pneumaticraft

**Comment by Alexthw46** [comment] 2023-02-18 14:57
should be fixed by https://www.curseforge.com/minecraft/mc-mods/starbunclemania/files/4400524, now buckets should work too

**Closed as completed by Alexthw46** 2023-02-18 14:57 UTC
